# Generated by Django 5.1.3 on 2024-11-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Component', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='Discribe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requrement',
            name='Dob',
            field=models.DateField(),
        ),
    ]
