# Generated by Django 5.1.3 on 2024-11-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Component', '0003_requrement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requrement',
            name='image',
        ),
    ]
